### Reset the demo
POST http://localhost:4001/api/system/reset

### Get all cases
GET http://localhost:4001/api/agencies/cphd.ca.gov/?sort=desc

### Add a random case
POST http://localhost:4001/api/agencies/cphd.ca.gov/random

### Add a 20 random cases
POST http://localhost:4001/api/agencies/cphd.ca.gov/random?numOfDays=2&numPerDay=10

### Add multiple random cases
POST http://localhost:4001/api/agencies/cphd.ca.gov/random?numOfDays=5&numPerDay=3000

### Publish cases
POST http://localhost:4001/api/agencies/cphd.ca.gov/publish

### Get the dictionary
GET http://localhost:4001/api/agencies/cphd.ca.gov/dictionary

### Change the dictionary
PUT http://localhost:4001/api/agencies/cphd.ca.gov/dictionary/us_caQuestion1
content-type: application/json

{
  "name": "us_caQuestion1",
  "namespace": "us_ca",
  "type": "string",
  "tags": [],
  "descriptions": [{
    "isoCultureCode": "en-us",
    "displayName": "CA Question 1",
    "section": "patient",
    "details": "pretend good local question"
  }]
}

###
DELETE http://localhost:4001/api/agencies/cphd.ca.gov/dictionary/us_caQuestion1

### Get all CDC events
GET http://localhost:4001/api/agencies/cdc.gov

### Get CDC dictionary
GET http://localhost:4001/api/agencies/cdc.gov/dictionary

### Get the subscriber
GET http://localhost:4001/api/agencies/cdc.gov/subscribers


### Read the feed once
POST http://localhost:4001/api/agencies/cdc.gov/subscribers/cases.cphd.ca.gov/read

### Start automatic feed reading
POST http://localhost:4001/api/agencies/cdc.gov/subscribers
content-type: application/json

{ "automatic": true }

### Stop automatic feed reading
POST http://localhost:4001/api/agencies/cdc.gov/subscribers
content-type: application/json

{ "automatic": false }

### Deduplicate the state feed
POST http://localhost:4001/api/agencies/cphd.ca.gov/deduplicate

### List feed
GET http://localhost:4001/api/feeds/metadata?prefix=

### List feed
GET http://localhost:4001/api/feeds/metadata?prefix=cphd.ca.gov/cases/snapshots/

### Get feed snapshot
GET http://localhost:4001/api/feeds/content?file=cphd.ca.gov/cases/snapshots/1.csv

### Get summary
GET http://localhost:4001/api/feeds/content?file=cphd.ca.gov/cases/summary.yaml

###
GET http://localhost:4001/api/feeds/content?file=cphd.ca.gov/cases/time_series/20221101T000000-07:00--P1M.csv
