### Reset the demo
POST http://localhost:3001/api/system/reset

### Get all cases
GET http://localhost:3001/api/stateCases?sort=desc

### Add a random case
POST http://localhost:3001/api/stateCases/random

### Add a 20 random cases
POST http://localhost:3001/api/stateCases/random?numOfDays=2&numPerDay=10

### Add multiple random cases
POST http://localhost:3001/api/stateCases/random?numOfDays=5&numPerDay=3000

### Publish cases
POST http://localhost:3001/api/stateCases/publish

### Get the dictionary
GET http://localhost:3001/api/stateCases/dictionary

### Change the dictionary
PUT http://localhost:3001/api/stateCases/dictionary/us_caQuestion1
content-type: application/json

{
  "name": "us_caQuestion1",
  "namespace": "us_ca",
  "type": "string",
  "tags": [],
  "descriptions": [{
    "isoCultureCode": "en-us",
    "displayName": "CA Question 1",
    "section": "patient",
    "details": "pretend good local question"
  }]
}

###
DELETE http://localhost:3001/api/stateCases/dictionary/us_caQuestion1

### Get all the cdcCases
GET http://localhost:3001/api/cdcCases

### Get CDC caseCases dictionary
GET http://localhost:3001/api/cdcCases/dictionary

### Get the subscriber
GET http://localhost:3001/api/cdcCases/subscriber

### Read the feed once
POST http://localhost:3001/api/cdcCases/subscriber/once'

### Start automatic feed reading
POST http://localhost:3001/api/cdcCases/subscriber
content-type: application/json

{ "automatic": true }

### Stop automatic feed reading
POST http://localhost:3001/api/cdcCases/subscriber
content-type: application/json

{ "automatic": false }

### Deduplicate the state feed
POST http://localhost:3001/api/stateCases/deduplicate

### List feed
GET http://localhost:3001/api/feed/metadata?prefix=/

### List feed
GET http://localhost:3001/api/feed/metadata?prefix=snapshots/

### Get feed snapshot
GET http://localhost:3001/api/feed/content?file=snapshots/1.csv

###
GET http://localhost:3001/api/feed/content?file=time_series/20221101T000000-07:00--P1M.csv
