### Reset the demo
POST http://localhost:3001/api/system/reset

### Get all cases
GET http://localhost:3001/api/stateCases?sort=desc

### Add a random case
POST http://localhost:3001/api/stateCases/random

### Add multiple random cases
POST http://localhost:3001/api/stateCases/random?numOfDays=3&numPerDay=5

### Publish cases
POST http://localhost:3001/api/stateCases/publish 
